.TH SIMILE 1 2013-07-31 simile
.SH NAME
simile \- a multi-paradigm graphical modelling environment

.SH SYNOPSIS
.B simile
[\fIOPTIONS\fR] [\fIfile\fR]

.SH DESCRIPTION
See http://simulistics.com/help for help using Simile.
This manpage only describes how to run it.

.SH OPTIONS
.TP
\fB\-stealth\fR
Runs Simile without checking or setting the in-use flag, so another instance can be run alongside.
.SH FILES
.I ~/.simile
.RS
Per user directory containing configuration files.
.SH BUGS
Support for accessibility options is incomplete.
.SH AUTHOR
Simulistics Ltd <support at simulistics dot com>

