package require Tktable

set keyValue tabular11510

# column widths
# format by column (or row)

global tcl_platform
################################################################################
# causes some Windows 98 machines to crash on slecting variables for plotter
# if {[string match windows $tcl_platform(platform)]} {
#     source ../System/lib/Extras/prntproc.tcl
# }
################################################################################

namespace eval $keyValue {
#    package require BWidget
    namespace import ::DisplayFormat::*

    variable displayFormat; # array of list $formatName $decimalplaces $ShowNegInRed
    # Lists of format names stored in the format array - array names are categories
    # PropertiesDlg uses these categorised lists to fill the list boxes
    # Format names correspond to procs of the same name that do the formatting.
    # Spaces are allowed in the format name and will be removed to compute the proc name
    # format($Category) $format
    variable format
    set format(Number) {General Fixed Scientific Percent}
    set format(Angle)  {DMS "Rad in DMS"}
    set format(Time)   { HHMM HHMMSS YYYYMMDDHHMMSS}
    set format(Date)   { YYYYMMDD YYYYMMDDHHMMSS}
    set format(Boolean) Boolean
    
    proc identify {} {
        return "Data table"
    }
    
    proc initialize {winId} {
        variable orientList
        set orientList($winId) {rows cols cols cols}
        variable displayList
        set displayList($winId) {}
        variable lastDisplay
        set lastDisplay($winId) 0.0
        variable displayUpdate
        set displayUpdate($winId) 1
        variable editMode
        
        menu $winId.formatMenu -tearoff 0 -postcommand \
                [namespace code [list AddVars $winId]]
        
        menu $winId.tablevars -tearoff 0 -postcommand \
                [namespace code [list AddVars $winId]]
        
        set toolbarItems [list \
                [list clear.gif "Clear" [namespace code "clear $winId"] ] \
                [list add.gif "Add a variable" \
                [namespace code "AddVariable $winId"]] \
                [list remove.gif "Remove a variable" \
                [namespace code "RemoveVariable $winId"]] \
                [list save.gif "Save to file" [namespace code "Save $winId"] ] \
                [list property.gif "Properties" [namespace code "PropertiesDlg $winId"] ] \
                [list refresh.gif Update [namespace code "Update $winId"]]]
        
        if {![string match .viewer $winId]} {
            ::graphtools::MakeToolBar $winId $toolbarItems
        }
        if {[info exists editMode($winId)]} {
            foreach surplus {0 1 2 5} {
                $winId.bbframe.buttonBox itemconfigure $surplus -state disabled
            }
        }
        
        scrollbar $winId.yscroll -command [list $winId.t yview]
        scrollbar $winId.xscroll -command [list $winId.t xview] \
                -orient horizontal
        
        pack [frame $winId.f] -fill both
        pack [label $winId.f.mess] ;# for instructions
        pack $winId.xscroll -side bottom -fill x
        pack $winId.yscroll -side right -fill y
        CreateTable $winId
        clear $winId ;# cos MRE can re-use same frame
        # note the above line is not intrusive
        SaveState $winId
    }
    
    proc Update {winId} {
        set topWin [winfo toplevel $winId]
        set origCursor [$topWin cget -cursor]
        $topWin configure -cursor watch
        update
        Reconbobulate $winId
        $topWin configure -cursor $origCursor
    }
    
    proc CreateTable {winId} {
        table $winId.t -rows 1 -cols 1 -variable data$winId -bg \#a0ffa0 \
	    -selectmode extended -sparsearray 0 \
	    -rowtagcommand [namespace code rowProc] \
	    -coltagcommand [namespace code colProc] \
	    -rowseparator \n -colseparator \t \
	    -yscrollcommand [list AdjustCanvas $winId t y] \
	    -xscrollcommand [list AdjustCanvas $winId f x] \
	    -browsecommand [namespace code [list EditCellIs %W %r %c]] \
	-selecttitle true
        
        pack $winId.t -fill both -expand true
        $winId.t tag configure red -fg red
        
        #	$winId.t set 0,0 Time
        #	$winId.t tag cell base 0,0
        #	$winId.t tag raise base
        #	$winId.t tag config base -fg black
        $winId.t tag config title -relief raised
        $winId.t tag config OddRow -bg \#e0ffe0
        $winId.t tag config OddCol -bg \#c0ffc0
    }
    
    proc Restore {winId} {
        variable displayList
        variable orientList
        variable displayFormat
        variable displayUpdate
        #variable colWidths
        
        set oldState [GetState $winId]
        initialize $winId
        set displayList($winId) [lindex $oldState 0]
        set orientList($winId) [lindex $oldState 1]
        foreach {id val} [lindex $oldState 2] {
            if {[string first , $id] != -1} { ;# generated by buggy version
                set id [lindex [split $id ,] 1]
            }
            set displayFormat($winId,$id) $val
        }
        set displayUpdate($winId) [lindex $oldState 3]
        if {[string match $displayUpdate($winId) {}]} {
           set displayUpdate($winId) 1
        }
        #set colWidths($winId) [lindex $oldState 4]
        #ShowMessage debug info "colWidths" ok
        #$winId.t width $colWidths($winId)
        display $winId [GetModelTime] 0 0
        SaveState $winId
    }
    
    proc SaveState {winId} {
        variable displayList
        variable orientList
        variable displayFormat
        variable editMode
        variable displayUpdate
        #variable colWidths
        
        #set colWidths($winId) [$winId.t width ]
        #ShowMessage debug info "colWidths" ok
        
        set clip [string length $winId,]
        set winDisplayFormat {}
        foreach {id val} [array get displayFormat $winId,*] {
            lappend winDisplayFormat [string range $id $clip end] $val
        }
        if {![info exists editMode($winId)]} {
            SetState $winId [list $displayList($winId) $orientList($winId) \
                    $winDisplayFormat $displayUpdate($winId)]
            #SetState $winId [list $displayList($winId) $orientList($winId) \
            #        $winDisplayFormat $displayUpdate($winId) $colWidths($winId)]
        }
    }
    
    proc AddVariable { winId } {
        $winId.f.mess config -text "Click on a variable in the Explorer window or a Model Diagram."
        GrabClicks $winId
    }
    
    proc RemoveVariable { winId } {
        tk_popup $winId.tablevars \
                [winfo pointerx $winId] [winfo pointery $winId]
    }
    
    proc ChangeFormat { winId } {
        tk_popup $winId.formatMenu \
                [winfo pointerx $winId] [winfo pointery $winId]
    }
    
    proc AddVars {winId} {
        variable displayList
        $winId.tablevars delete 0 end
        foreach var $displayList($winId) {
            if {[llength $var]} {
                $winId.tablevars add command -label $var \
                        -command [namespace code [list Remove $winId $var]]
            }
        }
    }

# we keep the values array and update it when a cell is edited. This means
# we do not lose precision when loading the edited array.
    proc EditCellIs {t row col} {
	variable editCell
	variable rowIds
	variable colIds
	variable values

	set winId [winfo parent $t]
	if {[info exists editCell($winId,lastVal)]} {
	    set newVal [set ::data${winId}($editCell($winId,lastRow),$editCell($winId,lastCol))]
	    if {![string equal $editCell($winId,lastVal) $newVal]} {
		foreach rowEntry [array names rowIds $winId,*] {
		    if {$rowIds($rowEntry)==$editCell($winId,lastRow)} {
			set rowsHeaders [lindex [split $rowEntry ,] 1]
			foreach colEntry [array names colIds $winId,*] {
			    if {$colIds($colEntry)==$editCell($winId,lastCol)} {
				set colsHeaders [lindex [split $colEntry ,] 1]
				set values($rowsHeaders,$colsHeaders) $newVal
			    }
			}
		    }
		}
	    }
	}
	set editCell($winId,lastRow) $row
	set editCell($winId,lastCol) $col
	set editCell($winId,lastVal) [set ::data${winId}($row,$col)]
    }
    
    proc Remove {winId var} {
        variable displayList
        variable dataStore
        variable orientList
        
        set ind [lsearch $displayList($winId) $var]
        set displayList($winId) [lreplace $displayList($winId) $ind $ind {}]
        foreach entry [array names dataStore $winId,$ind,*] {
            unset dataStore($entry)
        }
        set xScrollPosn [$winId.t xview]
        set yScrollPosn [$winId.t yview]
        Reconbobulate $winId
        switch [lindex $orientList($winId) 1] {
            rows {
                $winId.t xview moveto [lindex $xScrollPosn 0]
            } cols {
                $winId.t yview moveto [lindex $yScrollPosn 0]
            }
        }
    }
    
    proc click {winId node caption} {
        variable dataStore
        variable displayList
        variable lastDisplay
        variable orientList
        variable varNamePosns
        variable displayFormat
        
        ReleaseClicks $winId
        $winId.f.mess config -text {}
        set newHeader [GetCaptionPathFromId $node]
        set varIndex [lsearch $displayList($winId) $newHeader]
        set xScrollPosn [$winId.t xview]
        set yScrollPosn [$winId.t yview]
        if {$varIndex<0} {
            set varIndex [llength $displayList($winId)]
            lappend displayList($winId) $newHeader
            ################################################################################
            #             #ShowMessage debug info "[GetModelType $node]" ok
            #             # auto set display format doesn't work
            #             switch {[GetModelType $node]} {
            #                 INTEGER {set displayFormat($winId,$varIndex) {Fixed 0 0}}
            #                 FLAG    {set displayFormat($winId,$varIndex) {Boolean 4 0}}
            #                 default {set displayFormat($winId,$varIndex) {General 4 0}}
            #             }; # format dp Neg_in_red
            ################################################################################
            set displayFormat($winId,$varIndex) {General 4 0}; # format dp Neg_in_red
            if {[GetModelTime]==$lastDisplay($winId)} {
                set dataStore($winId,$varIndex,$lastDisplay($winId)) \
                        [GetTransVals $winId $node]
            }
            Reconbobulate $winId
            SaveState $winId
        }
        #puts "vi $varIndex"
        set lineToSee [lindex $varNamePosns($winId) $varIndex]
        if {[llength $lineToSee]} {
            #puts $lineToSee
            switch [lindex $orientList($winId) 1] {
                rows {
                    $winId.t see $lineToSee,0
                    $winId.t xview moveto [lindex $xScrollPosn 0]
                } cols {
                    $winId.t see 0,$lineToSee
                    $winId.t yview moveto [lindex $yScrollPosn 0]
                }
            }
        }
    }
    
    proc clear {winId} {
        variable dataStore
        variable editMode
        foreach entry [array names dataStore $winId,*,*] {
            unset dataStore($entry)
        }
        if {![info exists editMode($winId)]} {
            display $winId [GetModelTime] 0 0
        }
    }
    
    proc reset {winId} {
    }
    
    proc display {winId tCur tStep tRem} {
        variable dataStore
        variable displayList
        variable lastDisplay
        variable orientList
        variable displayUpdate
        
        set lastDisplay($winId) $tCur
        set varIndex 0
        foreach varCapt $displayList($winId) {
            if {[llength $varCapt]} { ;# check not deleted
                set varId [GetIdFromCaptionPath $varCapt]
                set dataStore($winId,$varIndex,$tCur) \
                        [GetTransVals $winId $varId]
                
            }
            incr varIndex
        }
        if {$displayUpdate($winId) || !$tStep} {
            set xScrollPosn [$winId.t xview]
            set yScrollPosn [$winId.t yview]
            Reconbobulate $winId
            switch [lindex $orientList($winId) 0] {
                rows {
                    $winId.t xview moveto [lindex $xScrollPosn 0]
                } cols {
                    $winId.t yview moveto [lindex $yScrollPosn 0]
                } none {
                    $winId.t xview moveto [lindex $xScrollPosn 0]
                    $winId.t yview moveto [lindex $yScrollPosn 0]
                }
            }
        }
    }
    
    proc GetTransVals {winId varId} {
        # this is not right, it should only get the trans table once
#        global userinfo
        set value [lindex [GetModelValue $varId] 0]
#        if {$userinfo(Version) >= 4.0} {
            set trans [GetTransTable $varId]
            return [TransEnums $trans $value]
#        } else {
#            return $value
#        }
    }
    
    proc CopyToClipboard {winId} {
        set titlecols [$winId.t cget -titlecols]
        set titlerows [$winId.t cget -titlerows]
        $winId.t configure -titlecols 0
        $winId.t configure -titlerows 0; # to allow all table to be selected by selection command
        $winId.t selection set origin end
        event generate $winId.t <<Copy>>
        $winId.t configure -titlecols $titlecols
        $winId.t configure -titlerows $titlerows
        # should deselect all cells
    }
    
    # save table contents as CSV file
    proc Save {winId} {
	global helperTable
        set types {
            {{Comma seperated values}       {.csv}        }
            {{All Files}        *             }
        }
        set filename [ChooseFile table.csv "Save table contents as.." 1 \
			  [$helperTable($winId,whichInstance) GetNode]]
        
        SaveToNamedFile $winId $filename
    }
    
    proc SaveToNamedFile {winId filename args} {
        global custom
        set rsep [$winId.t cget -rowseparator]
        set csep [$winId.t cget -colseparator]
        $winId.t configure -rowseparator \n -colseparator ,
        set titlecols [$winId.t cget -titlecols]
        set titlerows [$winId.t cget -titlerows]
        $winId.t configure -titlecols 0
        $winId.t configure -titlerows 0; # to allow all table to be selected by selection command
        $winId.t selection set origin end
        event generate $winId.t <<Copy>>
        set data [selection get -displayof $winId.t -selection CLIPBOARD]
        if {$filename != ""} {
	    if {[llength $args]} {
		set fileid [open $filename a]
		puts $fileid [lindex $args 0]
	    } else {
		set fileid [open $filename w]
	    }
            puts $fileid $data
            close $fileid
        }
        
        $winId.t configure -titlecols $titlecols
        $winId.t configure -titlerows $titlerows
        $winId.t configure -rowseparator $rsep -colseparator $csep
    }
    
    
    proc Print {winId} {ShowMessage Warning warning \
                "[identify] does not support printing.\n\
                However, you can copy the contents and paste them into another application for printing." ok
    }
    
    ################################################################################
    # requires prntproc.tcl
    #         proc Print {winId} {
    #             global printargs
    #             set hdc [printer dialog select]
    #             if { [lindex $hdc 1] == 0 } {
    #                 # User has canceled printing
    #                 return
    #             }
    #             set printargs(hDC) [ lindex $hdc 0 ]
    #
    #             set titlecols [$winId.t cget -titlecols]
    #             set titlerows [$winId.t cget -titlerows]
    #             $winId.t configure -titlecols 0
    #             $winId.t configure -titlerows 0; # to allow all table to be selected by selection command
    #             $winId.t selection set origin end
    #             event generate $winId.t <<Copy>>
    #             #ShowMessage debug info "[selection get -displayof $winId.t -selection CLIPBOARD]" ok
    #             set data [selection get -displayof $winId.t -selection CLIPBOARD]
    #             print_data $data
    #         $winId.t configure -titlecols $titlecols
    #         $winId.t configure -titlerows $titlerows
    #     }
    ################################################################################
    
    proc Reconbobulate {winId} {
        variable dataStore
        variable orientList
        variable displayList
        variable lastDisplay
        variable varNamePosns
        variable editMode
        
        variable values
        variable rowNames
        variable colNames
        variable rowIds
        variable colIds
        
        if {[info exists rowNames]} {unset rowNames}
        if {[info exists colNames]} {unset colNames}
        if {[info exists values]} {unset values}
        
        set varIndex 0
        foreach varCapt $displayList($winId) {
            if {[llength $varCapt]} { ;# check not deleted
                #		set dataStore($winId,$varIndex,$lastDisplay($winId)) empty
            }
            incr varIndex
        }
        
        foreach valId [array names dataStore $winId,*,*] {
            set valDims [split $valId ,]
            set varId [lindex $valDims 1]
            if {[string match none [lindex $orientList($winId) 0]]} {
                if {[lindex $valDims 2]==$lastDisplay($winId)} {
                    GrabIndices $winId 1 {} {} $varId $dataStore($valId) $varId
                }
            } else {
                GrabIndices $winId 0 {} {} [lindex $valDims 2] \
                        [list $varId $dataStore($valId)] $varId
            }
        }
        
        #puts "Data transferred to 2-d table mirror array"
#	ShowMessage debug info "Table has [llength [array names rowNames]] rows and [llength [array names colNames]] columns" ok
	set lineMax 10000
	set boxMax 1000000
	if {[llength [array names rowNames]]>$lineMax} {
	    set scaryFact tooManyRows
        }
	if {[llength [array names colNames]]>$lineMax} {
	    set scaryFact tooManyColumns
        }
	if {[llength [array names colNames]]*[llength [array names rowNames]]>$boxMax} {
	    set scaryFact tooManyCells
	    set lineMax $boxMax
        }
	if {[info exists scaryFact]} {
	    $winId.t configure -state normal
	    $winId.t set 0,0 "$::msgs(tableWimpOut)\n$::msgs($scaryFact) $lineMax"
	    $winId.t width 0 48
	    $winId.t height 0 2
	    $winId.t tag cell red 0,0
	    if {![info exists editMode($winId)]} {
		$winId.t configure -state disabled
	    }
	    return
	}

        set curHeaderRows 0
        set colList [lsort -command [namespace code ReComp] \
                [array names colNames]]
        foreach item $colList {
            set len [llength $item]
            if {$len>$curHeaderRows} {
                set curHeaderRows $len
            }
        }
        
        set curHeaderCols 0
        set rowList [lsort -command [namespace code ReComp] \
                [array names rowNames]]
        foreach item $rowList {
            set len [llength $item]
            if {$len>$curHeaderCols} {
                set curHeaderCols $len
            }
        }
        set levels [expr $curHeaderRows+$curHeaderCols]
        if {!$curHeaderRows} {set curHeaderRows 1}
        if {!$curHeaderCols} {set curHeaderCols 1}
        
        #puts "Header rows and columns counted"
        
        unset ::data$winId
        foreach {span old} [$winId.t spans] {
            $winId.t spans $span 0,0
        }
# Following is faster but flickers too much
#	destroy $winId.t
#	CreateTable $winId
        $winId.t config -rows $curHeaderRows -cols $curHeaderCols \
                -titlerows $curHeaderRows -titlecols $curHeaderCols
        set rowsTop 0
        set colsTop 0
        set hideTime [string match none [lindex $orientList($winId) 0]]
        set level $hideTime
        
        $winId.t configure -state normal
        while {$level-$hideTime < $levels} {
            switch $level {
                0 {set topCapt Time}
                1 {set topCapt Name}
                default {set topCapt "Index [expr $level-1]"}
            }
            
            if {$level<4} {set orient [lindex $orientList($winId) $level]}
            if {[string match rows $orient]} {
                set tgtSq [expr $curHeaderRows-1],$rowsTop
                set oldCapt [$winId.t get $tgtSq]
                if {[llength $oldCapt]} {
                    $winId.t set $tgtSq "$topCapt \\ $oldCapt"
                } else {
                    $winId.t set $tgtSq $topCapt
                }
                incr rowsTop
            } else {
                set tgtSq $colsTop,[expr $curHeaderCols-1]
                set oldCapt [$winId.t get $tgtSq]
                if {[llength $oldCapt]} {
                    $winId.t set $tgtSq "$oldCapt \\ $topCapt"
                } else {
                    $winId.t set $tgtSq $topCapt
                }
                incr colsTop
            }
            $winId.t tag cell base $tgtSq
            incr level
        }
        if {[info exists tgtSq]} {
            set rcolWidth [string length [$winId.t get $tgtSq]]
            if {$rcolWidth>10} {
                $winId.t width [expr $curHeaderCols-1] $rcolWidth
            }
            $winId.t tag raise base
            $winId.t tag config base -fg black
        }
        if {$curHeaderRows>1 && $curHeaderCols>1} {
            $winId.t spans 0,0 [expr $curHeaderRows-2],[expr $curHeaderCols-2]
        }
        #puts "Meta-headers inserted"
        set timeSide [lindex $orientList($winId) 0]
        set lineToShow 0
        set translateSide [lindex $orientList($winId) 1]
        set translateLevel [string match $translateSide \
                [lindex $orientList($winId) 0]]
        if {[string compare none $timeSide]} {
            set timeToShow [GetModelTime]
        }
        set varNamePosns($winId) {}
        
        set lastEntry(0) none
        set count $curHeaderRows
        foreach entry [array names rowIds $winId,*] {
            unset rowIds($entry)
        }
        foreach item $rowList {
            set rowIds($winId,$item) $count
            #            $winId.t insert rows end
            # changed to preserve widths/heights
            $winId.t config -rows [expr [$winId.t cget -rows]+1]
            set headerCol 0
            foreach headerElt $item {
                if {[string match $headerElt $lastEntry($headerCol)]} {
                    # header same as prev line so span it over
                    $winId.t spans $lastLine($headerCol),$headerCol \
                            [expr $count-$lastLine($headerCol)],0
                } else {
                    set lastEntry($headerCol) $headerElt
                    set lastEntry([expr $headerCol+1]) none
                    set lastLine($headerCol) $count
                    # For header columns, put in duplicate values that are spanned over
                    # so saved files can be used for file parameters
                }
                if {[string match rows $translateSide] && \
                            $headerCol==$translateLevel} {
                    set headerElt [lindex $displayList($winId) $headerElt]
                    if {!$headerCol} {
                        lappend varNamePosns($winId) $count
                    }
                }
                if {!$headerCol && [string match rows $timeSide] && \
                            $headerElt==$timeToShow} {
                    set lineToShow $count
                }
                $winId.t set $count,$headerCol \
                        [lindex [split $headerElt /] end]
                incr headerCol
            }
            incr count
        }
        #puts "Column headers inserted"
        set lastEntry(0) none
        set count $curHeaderCols
        foreach entry [array names colIds $winId,*] {
            unset colIds($entry)
        }
        foreach item $colList {
            set colIds($winId,$item) $count
            #            $winId.t insert cols end
            # changed to preserve widths/heights
            $winId.t config -cols [expr [$winId.t cget -cols]+1]
            
            set headerRow 0
            foreach headerElt $item {
                if {[string match $headerElt $lastEntry($headerRow)]} {
                    # header same as prev line so span it over
                    $winId.t spans $headerRow,$lastLine($headerRow) \
                            0,[expr $count-$lastLine($headerRow)]
                } else {
                    set lastEntry($headerRow) $headerElt
                    set lastEntry([expr $headerRow+1]) none
                    set lastLine($headerRow) $count
                    if {[string match cols $translateSide] && \
                                $headerRow==$translateLevel} {
                        set headerElt [lindex $displayList($winId) $headerElt]
                        if {!$headerRow} {
                            lappend varNamePosns($winId) $count
                        }
                    }
                    if {!$headerRow && [string match cols $timeSide] && \
                                $headerElt==$timeToShow} {
                        set lineToShow $count
                    }
                    $winId.t set $headerRow,$count \
                            [lindex [split $headerElt /] end]
                }
                incr headerRow
            }
            incr count
        }
        #puts "vnps $varNamePosns($winId)"
        #puts "row headers inserted"
	
	RestoreFromMirror $winId
        switch $timeSide {
            rows {
                $winId.t see $lineToShow,0
            } cols {
                $winId.t see 0,$lineToShow
            }
        }
        if {![info exists editMode($winId)]} {
            $winId.t configure -state disabled
        }
    }
    
    proc RestoreFromMirror {winId} {
	variable values
	variable rowIds
	variable colIds
        variable cellFormatKey
	variable displayFormat

        foreach value [array names values] {
            set headers [split $value ,]
            set rowHead $rowIds($winId,[lindex $headers 0])
            set colHead $colIds($winId,[lindex $headers 1])
	    set cellFormat $displayFormat($winId,$cellFormatKey($winId,$value))
            $winId.t set $rowHead,$colHead \
		[FormatValue $winId $values($value) [lindex $cellFormat 0] \
		     [lindex $cellFormat 1]]
            if {[lindex $cellFormat 2]==1 & $values($value)<0} {
                $winId.t tag cell red $rowHead,$colHead
            } else {
                $winId.t tag cell {} $rowHead,$colHead
	    }
        }
        #puts "Table values inserted"
    }

    # OK you thought that was tricky, now we need one to go the other way and
    # get the nested list format back from the table if it has been edited. What
    # are we working with? RowIds and ColIds list the table line for each set of
    # headers so we are probably best looping over these making an intermediate
    # array format (and perhaps picking out bounds) then converting that.
    
    proc ExtractEdits {winId} {
        variable rowIds
        variable colIds
        variable orientList
        variable indices
        variable values

        set rowsPt 0
        set colsPt 0
        set nonePt 0
        # First, make a command that will convert ids into array subscripts
        foreach level $orientList($winId) {
            if {![string match none $level]} {
                if {$rowsPt+$colsPt+$nonePt+1==[llength $orientList($winId)]} {
                    append subscriptTemplate \
                            "\[lrange \$${level}Headers [set ${level}Pt] end\]"
                } else {
                    append subscriptTemplate \
                            "\[list \[lindex \$${level}Headers [set ${level}Pt]\]\] "
                }
            }
            incr ${level}Pt
        }
        #puts "subscript template: $subscriptTemplate"
        #puts "rowIds [array get rowIds] colIds [array get colIds]"
        # next copy the 2-d table to an n-d array using these
        foreach value [array names values] {
	    set headers [split $value ,]
	    set rowsHeaders [lindex $headers 0]
	    set colsHeaders [lindex $headers 1]
	    set subscript [eval {concat} $subscriptTemplate]
	    set newValues($subscript) [EnquoteIfNonNumeric $values($value)]
	}
# Old version that actually got the values out the table widget
#        foreach rowEntry [array names rowIds $winId,*] {
#            set rowsHeaders [lindex [split $rowEntry ,] 1]
#            foreach colEntry [array names colIds $winId,*] {
#                set colsHeaders [lindex [split $colEntry ,] 1]
#                set subscript [eval {concat} $subscriptTemplate]
## puts "$subscriptTemplate evalled to $subscript"
#                set src ::data${winId}($rowIds($rowEntry),$colIds($colEntry))
#                if {[info exists $src]} {
#                    set newValues($subscript) [EnquoteIfNonNumeric [set $src]]
#                }
#            }
#        }
# puts "values: [array get values]"
        return [ArrayToList newValues]
    }
    
    proc ReComp {l1 l2} {
        if {[string match $l1 $l2]} {
            return 0
        }
        if {![llength $l1]} {
            return -1
        }
        if {![llength $l2]} {
            return 1
        }
        if {[string compare $l1 [lindex $l1 0]] || \
                    [string compare $l2 [lindex $l2 0]]} {
            set recurse [ReComp [lindex $l1 0] [lindex $l2 0]]
            if {$recurse} {
                return $recurse
            }
            return [ReComp [lrange $l1 1 end] [lrange $l2 1 end]]
        }
        if {[catch {expr ($l2<$l1)-($l2>$l1)} math]} {
            return [string compare $l1 $l2]
        }
        return $math
    }
    
    proc GrabIndices {winId depth rowsList colsList index struct varId} {
        variable orientList
        variable values
        variable rowNames
        variable colNames
        variable cellFormatKey
        
        if {[llength $index]} {
            set nextAxis [lindex $orientList($winId) [min $depth 3]]
            lappend ${nextAxis}List $index
            incr depth
        }
        
        if {[llength $struct] == 1} {
            set values($rowsList,$colsList) [lindex $struct 0]
            set cellFormatKey($winId,$rowsList,$colsList) $varId
            
            set rowNames($rowsList) {}
            set colNames($colsList) {}
        } else {
            foreach {newIndex newStruct} $struct {
                GrabIndices $winId $depth $rowsList $colsList $newIndex \
                        $newStruct $varId
            }
        }
    }
    
    proc rowProc row { if {$row>0 && $row%2} { return OddRow } }
    proc colProc col { if {$col>0 && $col%2} { return OddCol } }
    
    # FormatValue replaces VarPrecRender which is now DisplayFormat::General
    proc FormatValue {winId val format prec} {
        # if a c model is built with Windows math libraries, the numerical
        # values might not format as floats. Watch out for this problemette
        # and just return them as they are if it happens
        set format [regsub -all { } $format {}]; # spaces removed from format name to make a proc name
        switch $format {
            #General { General $val $prec}
            default { $format $val $prec}
        }
    }
    
    proc PropertiesDlg {winId} {
        variable orientList
        variable displayList
        variable format
        variable displayUpdate
        variable editMode
        variable dataStore
        
        set t [toplevel $winId.propertiesDlg]
        wm transient $t $winId
        wm title $t "Table properties"
        wm resizable $t 0 0
        set ::${t}l1 [lindex $orientList($winId) 0]
        set ::${t}l2 [lindex $orientList($winId) 1]
        set ::${t}l3 [lindex $orientList($winId) 2]
        set ::${t}l4 [lindex $orientList($winId) 3]
        set ::${t}l5 $displayUpdate($winId)
        
        set nb [::ttk::notebook $t.nb]
        pack $nb -expand on -fill both -padx 10 -pady 10
        
        # layout page
        set layoutP [frame $nb.layout]
	$nb add $layoutP -text Layout
        
        pack [label $layoutP.toplbl -text "For each possible dimension listed,\
                select between including it on the rows or on the columns of the table." \
                -wraplength 300] -pady 4
        
        pack [frame $layoutP.l1]  -anchor w -padx 2 -pady 4
        pack [label $layoutP.l1.lbl -text "Times:" -width 20] -side left  -anchor w
        pack [label $layoutP.l1.lbl2 -text "On Rows"] -side left -anchor w
        pack [radiobutton $layoutP.l1.rowb -variable ${t}l1 -value rows] -side left  -anchor w
        pack [label $layoutP.l1.coll -text "On Columns"] -side left -anchor w
        pack [radiobutton $layoutP.l1.colb -variable ${t}l1 -value cols] -side left -anchor w
        pack [label $layoutP.l1.nonel1 -text "Current values only"] -side left -anchor w
        pack [radiobutton $layoutP.l1.noneb -variable ${t}l1 -value none] -side left -anchor w
        
        pack [frame $layoutP.l2]  -anchor w -padx 2 -pady 4
        pack [label $layoutP.l2.lbl -text "Element names:" -width 20] -side left  -anchor w
        pack [label $layoutP.l2.lbl2 -text "On Rows"] -side left -anchor w
        pack [radiobutton $layoutP.l2.rowb -variable ${t}l2 -value rows] -side left  -anchor w
        pack [label $layoutP.l2.coll -text "On Columns"] -side left  -anchor w
        pack [radiobutton $layoutP.l2.colb -variable ${t}l2 -value cols] -side left  -anchor w
        
        pack [frame $layoutP.l3]  -anchor w -padx 2 -pady 4
        pack [label $layoutP.l3.lbl -text "First index:" -width 20] -side left  -anchor w
        pack [label $layoutP.l3.lbl2 -text "On Rows"] -side left -anchor w
        pack [radiobutton $layoutP.l3.rowb -variable ${t}l3 -value rows] -side left  -anchor w
        pack [label $layoutP.l3.coll -text "On Columns"] -side left  -anchor w
        pack [radiobutton $layoutP.l3.colb -variable ${t}l3 -value cols] -side left  -anchor w
        
        pack [frame $layoutP.l4]  -anchor w -padx 2 -pady 4
        pack [label $layoutP.l4.lbl -text "Other indices:" -width 20] -side left  -anchor w
        pack [label $layoutP.l4.lbl2 -text "On Rows"] -side left -anchor w
        pack [radiobutton $layoutP.l4.rowb -variable ${t}l4 -value rows] -side left  -anchor w
        pack [label $layoutP.l4.coll -text "On Columns"] -side left -anchor w
        pack [radiobutton $layoutP.l4.colb -variable ${t}l4 -value cols] -side left -anchor w
        
        pack [frame $layoutP.l5]  -anchor w -padx 2 -pady 4
        pack [checkbutton $layoutP.l5.update -variable ${t}l5 \
                -text "Update at display intervals"]
        
        #set newHeader [GetCaptionPathFromId $node]
        #set varIndex [lsearch $displayList($winId) $newHeader]
        
        # format page
        set formatP [frame $nb.format]
	$nb add $formatP -text "Variable Formats"
        set varF [frame $formatP.varF]
        pack $varF -side top -fill x
        
        set varL [label $varF.label -text Variable]
        set varCB [ttk::combobox $varF.comboBox -state readonly \
		       -values [concat All... $displayList($winId)]]
	$varCB current 0
        pack $varL $varCB -side left
        
        set formatF [frame $formatP.formatF]
        pack $formatF -side bottom -fill both -expand on -pady 10
        
        set catF [frame $formatF.catF]
        label $catF.label -text Category
        listbox $catF.listbox -exportselection false -selectmode single
        foreach cat [array names format] {
            $catF.listbox insert 0 $cat
        }
        pack $catF.label $catF.listbox -anchor w
        
        set formF [frame $formatF.formF]
        label $formF.label -text Format
        listbox $formF.listbox -exportselection off -selectmode single
        pack $formF.label $formF.listbox -anchor w
        
        # options
        set optionsF [labelframe $formatF.optionsF -text Options]
        
        frame $optionsF.decimalPlacesF
        pack [label $optionsF.decimalPlacesF.label -text "Decimal places"] -side left
        
        set DecimalPlacesSB [spinbox $optionsF.decimalPlacesF.decimalPlacesSB -from 0 -to 20 -width 5]
        pack $DecimalPlacesSB -side right
        
        set NegInRedCB [checkbutton $optionsF.negInRedCB -text "Show negative numbers in red"]
        pack $optionsF.decimalPlacesF $NegInRedCB -fill x -pady 15
        
        pack $catF $formF $optionsF -side left -padx 10 -fill y
        
	bind $varCB <ButtonRelease-1> [namespace code \
                "SetFormatWidgets $winId $varCB $catF.listbox $formF.listbox $optionsF"]
        bind $catF.listbox <ButtonRelease-1> +[namespace code \
                [list OnCatListBoxClick $winId $varCB $catF.listbox $formF.listbox]]
        bind $formF.listbox <ButtonRelease-1> +[namespace code \
                [list OnFormatListBoxClick $winId $varCB $formF.listbox]]
        
        SetFormatWidgets $winId $varCB $catF.listbox $formF.listbox $optionsF
        
        # buttons
        pack [frame $t.b]
        pack [button $t.b.ok -text OK -width 10 -command "set ${t}done 1"] \
                -side left -padx 2 -pady 4
        pack [button $t.b.cancel -text Cancel -width 10 -command "set ${t}done 0"] \
                -side left -padx 2 -pady 4
        ################################################################################
        #                 pack [button $t.b.apply -text Apply -width 10 \
        #                         -command [namespace code "Reconbobulate $winId"]] \
        #                 -side left -padx 2 -pady 4
        ################################################################################
        
# One of life's little mysteries. Unless you do the next three lines,
# it is impossible to switch between tabs on the Mac -- even though
# the same thing works fine in the equation dialogue.
        $nb select 1
	update
        $nb select 0
	grab $t
        tkwait variable ${t}done
        
        if {[set ::${t}done]} {
	    set newOrients [list [set ::${t}l1] [set ::${t}l2] \
                    [set ::${t}l3] [set ::${t}l4]]
            set displayUpdate($winId) [set ::${t}l5]
	    EditCellIs $winId.t 0 0 ;# get final edit
            if {[string equal $newOrients $orientList($winId)]} {
		RestoreFromMirror $winId
	    } else {
		# only do if table is editable
		if {[info exists editMode($winId)]} {
		    unset dataStore
		    # need tweaking if time/var in use
		    set dataStore($winId,0,0.0) [ExtractEdits $winId]
		}
		set orientList($winId) $newOrients
		Reconbobulate $winId
	    }
            SaveState $winId
        }
        destroy $t
    }
    
    
    
    proc SetCatListboxSelection {listbox formatSpec} {
        variable format
        
        set category ""
        $listbox selection clear 0 end
        foreach cat [array names format] {
            if {[lsearch $format($cat) $formatSpec]>=0} {
                set category $cat
                continue
            }
        }
        set catIndex [lsearch [$listbox get 0 end] $category]
        $listbox selection set $catIndex
    }
    
    proc SetFormatListboxSelection {listbox formatSpec} {
        $listbox selection set [lsearch [$listbox get 0 end] $formatSpec]
    }
    
    proc OnCatListBoxClick {winId varCB catListbox formListbox} {
        FillFormatListBox $catListbox $formListbox
        #$formListbox selection set 0; # can't get back from cancel - dlg should save state so can restore on cance
        #OnFormatListBoxClick $winId $varCB $formListbox
    }
    
    proc FillFormatListBox {catListbox formListbox } {
        variable format
        $formListbox delete 0 end
        foreach form $format([$catListbox get [$catListbox curselection]]) {
            $formListbox insert 0 $form
        }
    }
    
    proc OnFormatListBoxClick {winId varCB formatListbox} {
	AdjustCurrentFormatList $winId $varCB 0 \
	    [lindex [$formatListbox get 0 end] [$formatListbox curselection]]
    }
    
    proc SetFormatWidgets {winId varCB catlistbox formlistbox optionsF} {
        variable displayList
        variable displayFormat
	set varIndex [lsearch $displayList($winId) [$varCB get]]
        if {$varIndex==-1} {
	    set varIndex 0
	}
	set formatSpec [lindex $displayFormat($winId,$varIndex) 0]
	SetCatListboxSelection $catlistbox $formatSpec
	FillFormatListBox $catlistbox $formlistbox
	SetFormatListboxSelection $formlistbox $formatSpec
	$optionsF.decimalPlacesF.decimalPlacesSB set [lindex $displayFormat($winId,$varIndex) 1]
	if {[lindex $displayFormat($winId,$varIndex) 2]} {
	    $optionsF.negInRedCB select
	} else  {
	    $optionsF.negInRedCB deselect
	}
	$optionsF.decimalPlacesF.decimalPlacesSB configure -command \
	    [namespace code "AdjustCurrentFormatList $winId $varCB 1 %s"]
	$optionsF.negInRedCB configure -command \
	    [namespace code "OnNegInRedCBClick $optionsF.negInRedCB $winId $varCB"]
    }
    
    proc OnNegInRedCBClick {CB winId varCB} {
        global negInRedCB

	AdjustCurrentFormatList $winId $varCB 2 $negInRedCB
    }
    
    proc AdjustCurrentFormatList {winId varCB posn val} {
        variable displayList
        variable displayFormat

	set selected [$varCB get]
	set varIndex 0
	foreach varId $displayList($winId) {
	    if {[string equal $varId $selected] || \
		    [string equal "All..." $selected]} {
		lset displayFormat($winId,$varIndex) $posn $val
	    }
	    incr varIndex
	}
    }
} ;# end of namespace
