/* Module GUI_INPUT contains the code that supports the # environment-specific 
event processing code; this version is for SICStus # Prolog used in conjunction 
with the Tcl/Tk GUI extension. Most of these functions are simply passed straight 
on to the event handling module, as the form in which they are generated by Tk is 
identical to that in which they are used. Where this is the case, the calls from Tk
use goals that start with "tk_" to make the diffreence clear.
*/

sicstus_module(input, [tk_undo/2, tk_redo/2, tk_get_info/3,
		       tk_get_params/2, tk_bar_edit_menu/1, tk_click_obj/6,
		       tk_click/4, tk_doubleclick/4, tk_unclick/2, tk_drag/2,
		       tk_menu/3, tk_menu_select/2, tk_mode_select/1,
		       tk_resize_top_win/3, tk_visible/5,
		       tk_embrace/2, tk_abandon/0,
		       tk_abandon_eqn/0, compile_to_file/1,
		       tk_run_settings_tweaked/1, tk_off_window/1,
		       tk_kill_everything/1, tk_set_new_size/3,
		       tk_change_size/3, tk_do_colours/2]).

sicstus_use_module([library(lists), backup, event, menu]).

tk_undo(Cur, Wids) :-
	show_wait_cursor,
	nth0(Cur, Wids, Wid),
	finish_window_resize(Wid),
	undo_edit(Wid, Wids),
	show_normal_cursor.

tk_redo(Cur, Wids) :-
	show_wait_cursor,
	nth0(Cur, Wids, Wid),
	finish_window_resize(Wid),
	redo_edit(Wid, Wids),
	show_normal_cursor.

tk_get_info(Wid, Comp, What) :-
	get_info(Wid, Comp, What).

tk_get_params(Wid, Comp) :-
	get_params(Wid, Comp).

:- dynamic(log_interaction/0).

tk_bar_edit_menu(Wid) :-
	bar_edit_menu(Wid).

tk_click_obj(Wid, Action, Virt_X, Virt_Y, Name, CD) :-
/* Extra debugging data not put into save file while swapping to MDI
	into_save_file(tk_click_obj(Wid, Action, Virt_X, Virt_Y, Name)), */
	prioritize_window(Wid),
	finish_window_resize(Wid),
	(Action = click,
		click_obj(Virt_X, Virt_Y, Name, CD);
	Action = clicktext,
		click_text(Virt_X, Virt_Y, Name, CD);
	Action = doubleclick,
	    asserta(log_interaction),
	    doubleclick_obj(Virt_X, Virt_Y, Name),
	    retract(log_interaction)).

tk_click(Wid, Virt_X, Virt_Y, CD) :-
/*	into_save_file(tk_click(Wid, Virt_X, Virt_Y)), */
	prioritize_window(Wid),
	finish_window_resize(Wid),
	click(Virt_X, Virt_Y, CD).

tk_doubleclick(Wid, Virt_X, Virt_Y, _CD) :-
/*	into_save_file(tk_doubleclick(Wid, Virt_X, Virt_Y)), */
	show_wait_cursor,
	finish_window_resize(Wid),
	asserta(log_interaction),
	doubleclick(Virt_X, Virt_Y),
	retract(log_interaction),
	show_normal_cursor.

tk_unclick(_X, _Y) :- 
/*	into_save_file(tk_unclick(X, Y)), */
	unclick.

tk_drag(Virt_X, Virt_Y) :-
	drag(Virt_X, Virt_Y).

tk_menu(Window, Header, Item) :-
/*	into_save_file(tk_menu(Window, Header, Item)), */
    show_wait_cursor,
    (Window = '.hi.canvas', !;
     finish_window_resize(Window)),
    finish_old_edit(none),
    (menu_handle(Window, Header, Item); true),
    show_normal_cursor.

tk_menu_select(Obj_type, from_box) :-
/*	into_save_file(tk_menu_select(Obj_type, from_box) ), */
	show_wait_cursor,
	finish_old_edit(none),
	menu_select(Obj_type),
	show_normal_cursor.

tk_mode_select(Mode) :-
%%	into_save_file(tk_mode_select(Mode)),
	show_wait_cursor,
	finish_old_edit(none),
	mode_select(Mode),
	show_normal_cursor.

tk_resize_top_win(Wid, W, H) :-
	resize_top_win(Wid, W, H).

:- dynamic(resizing_windows/1).

tk_visible(Wid, L, T, R, B) :-
	(resizing_windows(Wid), !;
	    asserta(resizing_windows(Wid))),
	adjust_display_area(Wid, [L, T, R, B]).

finish_window_resize(Wid) :-
	\+ retract(resizing_windows(Wid)), !;
	state:Wid shows_model Model,
	finish_move(Model, 0).

tk_embrace(Wid, Comp) :-
	prioritize_window(Wid),
	embrace(Wid, Comp).

tk_abandon :-
	abandon.

tk_abandon_eqn :-
	abandon_eqn.

tk_set_new_size(Node, CType, New_size) :-
	set_box_size(Node, CType, New_size, 0,0).

tk_change_size(TopNode, CType, New_size) :-
	show_wait_cursor,
	set_box_size(TopNode, CType, New_size, 0,0),
	change_size(TopNode, CType, New_size),
	show_normal_cursor.

tk_run_settings_tweaked(Node) :-
	run_settings_tweaked(Node).

tk_off_window(Wid) :-
%%	into_save_file(tk_off_window(Wid)),
	finish_old_edit(none),
	off_window(Wid).

tk_kill_everything(Wid) :-
	kill_everything(Wid).

tk_do_colours(Node, Way) :-
	do_colours(Node, Way).
