# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

# JAT: this is very old, Windows vs Linux are decided by separate version
# numbers rather than checking [info sharedlibextension] -- note that in Win7
# the env is not necessaily passed to the execution thread

# All new for Simile 5.7: just offer what we have..,

scan [info tclversion] "%d.%d" MAJ MIN
set tail [info sharedlibextension]
if {[string equal .dll $tail]} {
    set head {}
    set mid {}
} else {
    set head lib
    set mid .
}
    
foreach comp {ame_dll unpacker} {
    set shareLib [file join $dir $head$comp$MAJ$mid$MIN$tail]
    if {[file exists $shareLib]} {
	package ifneeded [string totitle $comp] $MAJ.$MIN [list load $shareLib]
    }
}
