# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

# JAT: this is very old, Windows vs Linux are decided by separate version
# numbers rather than checking [info sharedlibextension]

global env
scan [info tclversion] "%d.%d" MAJ MIN
if {![catch {set vers $env(SIMILE_VERSION)}]} {
    package ifneeded Ame_dll $MAJ.$MIN.$vers.0 \
	[list load [file join $dir ame_dll$MAJ$MIN.dll]]
    package ifneeded Ame_dll $MAJ.$MIN.$vers.1 \
	[list load [file join $dir libame_dll$MAJ.$MIN$env(slTail)]]

    if {[string equal .dll $env(slTail)]} {
	package ifneeded Unpacker $vers \
	    [list load [file join $dir unpacker$MAJ$MIN$env(slTail)]]
    } else {
	package ifneeded Unpacker $vers \
	    [list load [file join $dir libunpacker$MAJ.$MIN$env(slTail)]]
    }
}
