# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

# JAT: this is very old, Windows vs Linux are decided by separate version
# numbers rather than checking [info sharedlibextension] -- note that in Win7
# the env is not necessaily passed to the execution thread

# All new for Simile 5.7: just offer what we have..,

scan [info tclversion] "%d.%d" MAJ MIN
set extn [info sharedlibextension]
if {[string equal .dylib $extn]} {
    set tail _mac$extn
} else {
    set tail $extn
}
if {[string equal .dll $tail]} {
    set head {}
    set ins {}
} else {
    set head lib
    set ins .
}
    
foreach comp {ame_dll unpacker} {
    foreach shareLib [glob [file join $dir $head$comp*$tail]] {
	set vgo [string length [file join $dir $head$comp]]
	set maj [string range $shareLib $vgo $vgo]
	set min [string range $shareLib [incr vgo [string length n$ins]] \
		     end-[string length $tail]]
	set vers $maj.$min
	package ifneeded [string totitle $comp] $vers [list load $shareLib]
    }
}

# Other non-auto-installable cross-platform TclTk extensions do not go
# here because this file is included in Linux distributions but such
# packages are built and installed in separate subdirectories, so
# trying to load them here breaks it

