package provide SimileAutoObj 1.0

# Notes
# must be pipe interface
# must be in the Simile distribution tree

# todo
# ModelWindowImpl expose more hai2mmii.tcl
# update SetValue code to use global arrays
#
# RunControlImpl  need to set submodel timesteps
#    SetExecuteFor DOESN'T EFFECT RUN!!!!!!!!!!!!!!!

# Should abstract common helper behaviour, e.g. clear, hide and show


package require Itcl
namespace import ::itcl::*

if {[string match windows $tcl_platform(platform)]} {
    package require tcom
    ::tcom::import [file join [file dirname [info script]] SimileAutoObj.tlb]
}

package require Tk


set SimileAutoObjLoaded true; # used so .register (welcome) dialog not produced

###############################################################################
set argc 0; # simile.tcl expects to be called from the command line - tell it no args
source "[pwd]/../../Run/simile.tcl"
#puts "sourced"
###############################################################################


class ModelWindowImpl {
    
    #variable winId ?init
    
    private method GetModelWindow {} {
        global window_info
        return $window_info([lindex [lsort [array name window_info *,parent]] 0])
    }
    
    public method CreateHelperWindow {helperId helperTitle} {
        set winId [NewHelperWindow node00000 $helperId $helperTitle]
        ${helperId}::initialize $winId
        if {[PrefValue custom(helperManager) helperManager]} {
            ::RunEnv::ChildrenFocusParent $winId
        }
        return $winId
    }
    
    constructor {} {
        Hide
    }
    
    public method Hide {} {
        # SHOULD IT SHOW ALL WINDOWS!!!!!!!!
        wm withdraw [GetModelWindow]
    }
    
    public method Show {} {
        # SHOULD IT SHOW ALL WINDOWS!!!!!!!!
        wm deiconify [GetModelWindow]
    }
    
    public method UseMRE {bool} {
        # IS THIS GOING TO HAVE A TYPE PROBLEM???
        global custom
        set custom(helperManager) $bool
    }
    
    # File Menu
    public method FileNew {} {
        MenuSelect [GetModelWindow].canvas file new
    }
    
    public method FileOpenDlg {} {
        MenuSelect [GetModelWindow].canvas file
    }
    
    public method FileOpen {modelFile} {
        Reopen [GetModelWindow].canvas $modelFile reopen
    }
    
    public method FileSave {} {
        MenuSelect [GetModelWindow].canvas file save
    }
    
    public method FileSaveAs {} {
        MenuSelect [GetModelWindow].canvas file save_as
    }
    
    public method FilePrint {} {
        MenuSelect PrintNow [GetModelWindow].canvas
    }
    
    public method FileExportModel {} {
        MenuSelect [GetModelWindow].canvas file export_prolog
    }
    
    public method FileExportCPPCodeExec {} {
        MenuSelect [GetModelWindow].canvas file compile_c
    }
    
    public method FileExportPostscript {} {
        DoWithErrors ExportPostscript [GetModelWindow].canvas
    }
    
    private method Exit {} {
        # DOESN'T WORK
        byebye [GetModelWindow]
        # prolog tk_finish; # generates existance error
    }
    
    # Edit Menu - not supporting editing the model
    public method Preferences {} {
        Pref_Dialog
    }
    
    # Model Menu
    public method BuildCPP {} {
        # builds the model with CPP and returns a run control command/object
        MenuSelect [GetModelWindow].canvas file run_c
        set rc [RunControlImpl ::runControl $this]
        return $rc
    }
    
    public method BuildTcl {} {
        # builds the model with Tcl and returns a run control command/object
        MenuSelect [GetModelWindow].canvas file run_tcl
        set rc [RunControlImpl ::runControl $this]
        return $rc
    }
    
    public method ListEquations {} {
        MenuSelect [GetModelWindow].canvas file list_eqns
    }
}

class RunControlImpl {
    
    variable winId;    #Tk path to RunControl window
    variable keyvalue; # RunControl namespace
    variable modelNode node00000
    
    constructor {modelWindow} {
        global runState
        global helperTable
        set keyvalue $helperTable(RunControl)
        set winId $runState($modelNode,helperId)
        Hide
    }
    
    public method Show {} {
        wm deiconify $winId
    }
    
    public method Hide {} {
        wm withdraw $winId
    }
    
    public method Run {} {
        # returns the time to complete (to run the simulation)
        set timestr [time [list ${keyvalue}::SetMode $winId start]]
        set musec [lindex $timestr 0]
        return "[expr {$musec/1e6}] sec"
    }
    
    public method Reset {} {
        ${keyvalue}::SetMode $winId reset
    }
    
    # No point in a stop command as the Run is not script interuptable
    #public method Stop {} {
    #    ${keyvalue}::SetMode $winId stop
    #}
    
    public method SetTimeUnits {units} {
        # units: unit second minute hour day week month year Ma
        global runState
        set runState($modelNode,timeUnit) $units
    }
    
    public method GetTimeUnits {} {
        global runState
        return $runState($modelNode,timeUnit)
    }
    
    public method GetIntegrationMethod {} {
        global runState
        return $runState($modelNode,intMethod)
    }
    public method SetIntegrationMethod {method} {
        global runState
        set runState($modelNode,intMethod) $method
    }
    
    public method SetIntegrationMethodEuler {} {
        global runState
        set runState($modelNode,intMethod) Euler
    }
    
    public method SetIntegrationMethodRungeKutta {} {
        global runState
        set runState($modelNode,intMethod) {4th-order Runge-Kutta}
    }
    
    public method SetExecuteFor {time} {
        global runState
        set runState($modelNode,execTime) $time
    }
    
    public method GetExecuteFor {} {
        global runState
        return $runState($modelNode,execTime)
    }
    
    public method GetCurrentTime {} {
        global runState
        return $runState($modelNode,currentTime)
    }
    
    public method SetDisplayInterval {timeStep} {
        global runState
        set runState($modelNode,displayInt) $timeStep
    }
    
    public method GetDisplayInterval {} {
        global runState
        return $runState($modelNode,displayInt)
    }
    
    public method GetNumberOfTimeSteps {} {
        return [GetPhaseCount $modelNode]
    }
    
    public method SetTimeStep {number timestep} {
        global runState
        if {0<$number && $number<=[GetPhaseCount $modelNode]} {
            set runState($modelNode,update${number}) $timestep
        } elseif {$number==0 || $number==-1}  {
            puts "Timestep 0 and -1 cannot be specified."
        } else  {
            puts "Timestep $number is not in use."
        }
    }
    
    public method GetTimeStep {number} {
        global runState
        if {0<$number && $number<=[GetPhaseCount $modelNode]} {
            return $runState($modelNode,update${number})
        } elseif {$number==0 || $number==-1}  {
            puts "Timestep 0 and -1 cannot be specified."
        } else  {
            puts "Timestep $number is not in use."
        }
    }
    
    public method GetValue {path} {
        global runState
        set winId $runState(node00000,helperId)
        return [GetModelValue $winId [GetIdFromCaptionPath $winId $path]]
    }
    
    public method SetValue {path value} {
        global runState
        # CHECK IF INPUT VARIABLE OR COMPARTMENT AND WARN IF NOT
        set winId $runState(node00000,helperId)
        SetModelValue $winId [GetIdFromCaptionPath $winId $path] $value
        return [GetModelValue $winId [GetIdFromCaptionPath $winId $path]]
    }
    
    public method SetValueNew {path value} {
        global runState
        # CHECK IF INPUT VARIABLE OR COMPARTMENT AND WARN IF NOT
        set winId $runState(node00000,helperId)
        SetModelValue $winId [GetIdFromCaptionPath $winId $path] $value
        return [GetModelValue $winId [GetIdFromCaptionPath $winId $path]]
    }
    
    public method GetMinValue {path} {
        global runState
        set winId $runState(node00000,helperId)
        return [::GetMinValue $winId [GetIdFromCaptionPath $winId $path]]
    }
    
    public method GetMaxValue {path} {
        global runState
        return [::GetMaxValue $winId [GetIdFromCaptionPath $winId $path]]
    }
    
    #paths
    public method GetModelType {} {
        return [GetModelType $winId $modelNode]
    }
    
    public method GetModelEval {} {
        return [GetModelEval $winId $modelNode]
    }
    
    public method GetModelDims {} {
        return [GetModelDims $winId $modelNode]
    }
    
    public method GetModelClass {} {
        return [GetModelClass $winId $modelNode]
    }
    
    public method GetObjectList {} {
        return [GetObjectList $winId]
    }
    
    public method GetPhaseCount {} {
        return [GetPhaseCount $modelNode]
    }
    
}

################################################################################
# class ModelExplorerImpl  {
#     constructor {modelWindow} {
#         return [$modelWindow CreateHelperWindow ModelInspector63654 {Model Explorer}]
#     }
# }
################################################################################

class TableHelperImpl {
    variable winId;    #Tk path to Table helper window
    variable keyvalue; # Table helper namespace
    variable modelNode node00000
    
    constructor {modelWindow} {
        global runState
        global helperTable
        set keyvalue tabular11510
        set winId [$modelWindow CreateHelperWindow $keyvalue {Table}]
        Hide
        SetUpdateAtDisplayInterval false
    }
    
    destructor {
        destroy $winId
    }
    
    public method Show {} {
        wm deiconify $winId
    }
    
    public method Hide {} {
        wm withdraw $winId
    }
    
    public method AddVariable {path} {
        global helperTable
        set helperTable(node00000,current) $winId
        ${keyvalue}::click $winId [GetIdFromCaptionPath $winId $path] $path
    }
    
    public method RemoveVariable {path} {
        set var $path; # prop needs nodeId TODO
        ${keyvalue}::Remove $winId $var
    }
    
    public method Clear {} {
        $keyvalue::clear
    }
    
    public method SetUpdateAtDisplayInterval {value} {
        set ${keyvalue}::displayUpdate($winId) $value
    }
    
    public method GetUpdateAtDisplayInterval {} {
        return  ${keyvalue}::displayUpdate($winId)
    }
    
    public method Update {} {
        ${keyvalue}::Update $winId
    }
    
    public method SaveToFile {filename} {
        Update
        ${keyvalue}::SaveToNamedFile $winId $filename
    }
    
}

if {[string match windows $tcl_platform(platform)]} {
    ::tcom::object registerfactory ::SimileAutoObj::ModelWindow {ModelWindowImpl #auto} {delete object}
}

