package provide SimileAutoObj 1.1
# 1.0 for Simile 4.0
# 1.1 for Simile 4.1

# Notes
# must be pipe interface

package require Itcl

package require Tk

if {[string match windows $tcl_platform(platform)]} {
# removed until I can get hold of a 64-bit version
#     package require tcom
#     ::tcom::import [file join [file dirname [info script]] SimileAutoObj.tlb]
}
set ::SimileAutoObjLoaded true; # used so .register (welcome) dialog not produced
set env(LD_LIBRARY_PATH) "[file dirname [info script]]/../../../System/lib"
if {![info exists window_info]} {
    set argc 1; # simile.tcl expects to be called from the command line -- 
# the '-stealth' arg allows other instances of Simile to run independently
    set argv {-stealth}
    source "[file dirname [info script]]/../../../Run/simile.tcl"
    
    rename exit ::renamed::exit
    proc exit {} {
        prolog tk_kill_everything(_)
    }
    
# This section no longer required, because:
# (a) ShowMessage is now used only for debugging, not for user interaction -- 
# that is all done through Query which has built-in scripted execution mode
# (b) It is now called ShowMess for consistency with the c extensions.
#    rename ShowMessage ::renamed::ShowMessage
#    proc ShowMessage { title icon string resps {parent {}}} {
#        puts "$icon $title: $string"
#        switch -- $resps {
#            abortretryignore {
#                return abort
#            }
#            ok {
#                return ok
#            }
#            okcancel{
#                return ok
#            }
#            retrycancel {
#                return cancel
#            }
#            yesno {
#                return yes
#            }
#            yesnocancel {
#                return yes
#            }
#        }
#        
#    }
#}
#
if {[string match windows $tcl_platform(platform)]} {
    #tk_messageBox -message "ModelWin before registerfactory"
    #::tcom::object registerfactory ::SimileAutoObj::ModelWindow {similescript::ModelWindow #auto} {delete object}
    #::tcom::object registerfactory ::SimileAutoObj::RunControl {similescript::RunControl  #auto} {delete object}
    #::tcom::object registerfactory ::SimileAutoObj::TableHelper {similescript::TableHelper  #auto} {delete object}
    #tk_messageBox -message "ModelWin after registerfactory"
}


