#!/bin/sh
# script that finds its own arse, using both hands and a map if necessary,
# and launches Simile from surrounding directories

if expr "$0" : '.*/'; then
    # program invoked by filename
    OLDDIR=`pwd`
    cd "`dirname "$0"`"
    LOC=`pwd`/`basename "$0"`
    cd "$OLDDIR"
else
    # program invoked by command: find target
    LOC=`which $0`;
fi

LSLINE=`ls -l "$LOC"`
LINK=`expr "$LSLINE" : '.* -> \(.*\)$'`

if test -z "$LINK"; then
    # target is not a symlink
    TOP="$LOC";
elif expr "$LINK" : '[/~]'; then
    # symlink to absolute path
    TOP="$LINK";
else
    # relative symlink
    TOP=`dirname "$LOC"`/$LINK;
fi

RUNDIR=`dirname "$TOP"`;
SIMDIR=`dirname "$RUNDIR"`;
LD_LIBRARY_PATH="$SIMDIR/System/lib"
export LD_LIBRARY_PATH
TCL_LIBRARY="$LD_LIBRARY_PATH/tcl8.4"
export TCL_LIBRARY
"$SIMDIR/System/bin/wish" "$SIMDIR/Run/simile.tcl" $1
