/* version needs its own special procedure because any other might change
   and cause a crash before version mismatch is detected */
FINDABLE EXPORT getversion_type get_version;
FINDABLE EXPORT double get_version() {
  double simile_version;
  sscanf(strstr(simile_identifier,"version="), "version=%lf", &simile_version);
  return(simile_version);
}

jmp_buf env;

static void exit_sighandler(int x){
  longjmp(env, x);
}

// old version declared wrapper function for loading by dlfcn
// FINDABLE EXPORT evalmodel_type do_evalmodel;
// FINDABLE EXPORT int do_evalmodel(InstanceOfModel* handle, int phase) {

// now however it is a class method
int AME_model::do_evalmodel(int phase) {
  // Dont want a crash while running model to terminate Simile, so add 
   // handler. This has to be done on reset cos using the handler in some OS
   // causes it to be unset, and a reset can restart a crashed model.
  if (phase <= 0) {
    signal(SIGSEGV,exit_sighandler);
  }

  dts[0] = phase; // so external code can access it
  if (userStop.excpNo = -setjmp(env)) {
    return 1;
  } else {
// InternalStop not used so no need for try/catch layer
//    try {
      evalmodel(phase);
//    }
//    catch (int error) {
//      return error;
//    }
//    catch (InternalStop notice) {
      // used if stop_on_id throws exception
//      userStop.targetId = notice.lineNo;
//      userStop.excpNo = notice.userCode;
//    }
    return userStop.excpNo;
  }
}

FINDABLE EXPORT createmodel_type do_createmodel;
FINDABLE EXPORT InstanceOfModel* do_createmodel(ExecutingModel* outerRef) {
  // AME_model constructor is generated by Simile, so initialize clientref here
  InstanceOfModel* newInst;
  newInst = (InstanceOfModel*)new AME_model;
  newInst->partner = outerRef;
  char mess[255];
  // sprintf(mess, "Model .dll setting partner to %lx", (long)outerRef);
  // suppShowMess(mess);
  return newInst;
}

//FINDABLE EXPORT updatemodel_type do_updatemodel;
//FINDABLE EXPORT void do_updatemodel(InstanceOfModel* handle, int phase) {
//  ((AME_model *)handle)->updatemodel(phase);
//}
//
//FINDABLE EXPORT advancemodel_type do_advancemodel;
//FINDABLE EXPORT void do_advancemodel(void* handle, int phase) {
//  ((AME_model *)handle)->advancemodel(phase);
//}
//
//FINDABLE EXPORT exitmodel_type do_exitmodel;
//FINDABLE EXPORT void do_exitmodel(InstanceOfModel* handle) {
//  handle->do_exitmodel();
//  delete handle;
//}
//
//int at_time_step () {
//  return glob_element(dts,0)<=1;
//}
//
int InstanceOfModel::loses (double prob, int phase) {
  /* kills_per_step was intended to make sure that for R-K the same proportion 
     get killed in four passes as in a single pass for Euler. As of 5.7 we make
     sure the loss process only happens once per time step. */
//  int kills_per_step;
  if (prob<=0 || ts[0]<0) {
    return 0;
  } else if (prob>=1) {
    return 1;
  } else {
//    kills_per_step=glob_element(ts,0)?4:1;
//    return ame_rand(0,1)>pow(1-prob,glob_element(dts,phase)/kills_per_step);
    return ame_rand(0,1)>pow(1-prob,dts[phase]);
  }
}

double InstanceOfModel::stage_incr (diffs *extras, int step, 
				    double v, double span, int graphId) {
  double dv, result, errMagn;

  /*
In this version, the three intermediate increments are kept in t1-t3 while
building the full R-K increment. After this is complete they are assigned:
t1 = initial rate of change (used when redoing step with different dt)
t2 = last increment (used to undo step)
t3 = estimate of next initial increment
  */
  if (ts[0]<0) {
    dv = extras->t1*dts[step];
  } else {
    dv = v*dts[step];
  }
  switch (int(ts[0])) {
  case 0: // Euler
    extras->t1 = v;
    extras->t2 = dv;
    return (extras->t3 = dv);
  case 1: // these 4 are R-K
    return (extras->t1 = dv)/2;
  case 2:
    return ((extras->t2 = dv) - extras->t1)/2;
  case 3:
    return (extras->t3 = dv) - extras->t2/2;
  case 4:
    extras->t2 = (extras->t1 + 2*extras->t2 + 2*extras->t3 + dv)/6;
    result = extras->t2 - extras->t3;
    extras->t3 = (-extras->t1 + 2*extras->t3 + 2*dv)/3;
    extras->t1 = extras->t1/dts[step];
    return result;
  case -1: // undoes previous change Euler
    result = extras->t2;
    extras->t3 = dv;
    return (extras->t2 = dv)-result;
  case -2: // undoes previous change R-K
    return (extras->t1 = dv)/2 - extras->t2;
  case 10: case 11: // does not change compartment, just checks for errors
    errMagn = fabs(dv-extras->t3)*100/span;
    if (errMagn>adapt_maxerr) {
      userStop.targetId = graphId;
      adapt_maxerr = errMagn;
    }
    return 0;
  };
};

#define   CHECK_LOWER   1
#define   CHECK_UPPER   2
int InstanceOfModel::check_limit (double trigger, double lower, double upper,
				  int action, int graphId, 
				  int step, diffs* extras) {
  double old, to_limit, rate, prediction;
  BOOLEAN for_real;
  int heading_out, phase = int(ts[0]);

  switch (phase) {
  case 0: case 1: // resetting model, do not use saved data
    extras->t1 = trigger; // for prediction next step
    // go = (to_limit < 0); events on init = nothing but trouble
    break;
  case 2: // next 3 are R-K substeps
    extras->t2 = trigger;
    break;
  case 3:
    extras->t2 = (extras->t2+trigger)/2;
    break;
  case 5: // setting model rates for real -- euler
  case 6: // setting model rates for real -- R-K
  case 10: // error checking -- euler
  case 11: // error checking -- R-K
    old = extras->t1;
    if (trigger>old && (action & CHECK_UPPER)) {
      heading_out = 1;
      to_limit = upper-trigger;
      rate = trigger-old;
    } else if (trigger<old && (action & CHECK_LOWER)) {
      heading_out = -1;
      to_limit = trigger-lower;
      rate = old-trigger;
    } else
      heading_out = 0;
    
    for_real = (phase==5 || phase==6);
    if (for_real) 
      extras->t1 = trigger; // for prediction next step
    if (heading_out) { // make prediction for this event
      if (phase==6 || phase==11) { // ok approximate to quadratic
	// printf("old %f mid %f new %f\n", old, extras->t2, trigger);
	double a,b,det;
	a=-heading_out*2*(trigger-2*extras->t2+old)/pow(dts[step],2);
	if (a==0) // it is linear
	  prediction = ts[step] + dts[step]*to_limit/rate;
	else {
	  b=-heading_out*(3*trigger-4*extras->t2+old)/dts[step];

	  // that is the eqn for the curve. Determinant:
	  det = pow(b,2)-4*a*to_limit;
	  if (det<=0) return 0; // no misses or grazes
	  det = pow(det,0.5);
	  // printf("a %f b %f c %f det %f\n", a, b, to_limit, det);
	  if (to_limit*dts[step]>0) // inside limit XOR going backwards
	    prediction = ts[step] + (-b - det)/(2*a);
	  else // take later root
	    prediction = ts[step] + (-b + det)/(2*a);
	}
      } else // phase is 5 or 10, do linear extrap
	prediction = ts[step] + dts[step]*to_limit/rate;

      if (for_real && to_limit <= 0) { // do event
	userStop.targetId = graphId; // for pause-on-event reporting
	return heading_out; // culprit is actual event
      } else if (prediction<event_predict) {
	event_predict = prediction;
	// if (!for_real) // for error reporting
	  // userStop.targetId = graphId; // culprit is predicted event
      }
    } else if (dts[0]<=0 || !extras->t3) 
      // resetting or in a new instance -- fire if out of range
      if (trigger>=upper) 
	return extras->t3 = 1;
      else if (trigger<=lower)
	return extras->t3 = -1;
      else
	extras->t3 = 10; // indicate no longer new instance
  }
  return 0;
}

template <class modeldata> 
modeldata InstanceOfModel::retract_from_pipe(delay<modeldata>* extras) {
  int phase = int(ts[0]);
  BOOLEAN for_real = (phase==5 || phase==6);
  double time = ts[phasecount];

  if (dts[0]>0)
    return extras->retract(time, for_real);
  else
    extras->empty();
  return 0;
}

template <class modeldata> 
void InstanceOfModel::insert_to_pipe(delay<modeldata>* extras, 
					  double wait, 
					  modeldata payload) {
  int phase = int(ts[0]);
  BOOLEAN for_real = (phase==5 || phase==6);
  double time = ts[phasecount];

  extras->insert(time+wait, for_real?payload:0, &event_predict);
}

/* This is called only when we create the type, to return model constants */
FINDABLE EXPORT getcount_type get_count;
FINDABLE EXPORT int get_count(void* ame_rand_ptr, 
			      void* graphpoint_ptr, 
			      void* release_graph_data_ptr, 
			      void* compare_instance_status_ptr, 
			      void* model_requests_file_param_ptr, 
			      void* stat_check_ptr,
			      void* showMess_ptr,
			      void* graph_ptr, 
			      int* phases, node_data_line** data_ptr) {
  /* Stub is giving us function pointers to save us using the linker... */
  ame_rand_ref = (ame_rand_type*)ame_rand_ptr;
  graphpoint_ref = (graphpoint_type*)graphpoint_ptr;
  release_graph_data_ref = (release_graph_data_type*)release_graph_data_ptr;
  compare_instance_status = 
    (compare_instance_status_type*)compare_instance_status_ptr;
  model_requests_file_param = 
    (model_requests_file_param_type*)model_requests_file_param_ptr;
  /*  fetch_instance_ref = (fetch_instance_type*)fetch_instance_ptr;
  update_submodel_ref = (update_submodel_type*)update_submodel_ptr;
  advance_submodel_ref = (advance_submodel_type*)advance_submodel_ptr;
  eval_submodel_ref = (eval_submodel_type*)eval_submodel_ptr;
  search_from_ref = (search_from_type*)search_from_ptr;
  advance_ptr_ref = (advance_ptr_type*)advance_ptr_ptr;
  get_remote_value = (get_remote_value_type*)get_remote_value_ptr;
  */
  stat_check = (stat_check_type*)stat_check_ptr;
  suppShowMess = (show_model_mess_type*)showMess_ptr;
  
  graph_data_pointer = (graph_data_type**)graph_ptr;

  /* ...and we are telling stub... */
  *phases = phasecount;
  *data_ptr = nodedata;
/*  *arc_count = (sizeof inputArcs)/sizeof(char*)-1; // don't include filler
  *arc_id_list = inputArcs;
  *adapt_maxerr = &maxerr;
  *userDefStop = &userStop; */
  return((sizeof nodedata)/sizeof(node_data_line));
}

/**********************************************************************/

/*
con la LoadLibrary e la pstub sono inutili, facciamo rifermento direttamente alle orinali!
extern "C" double __stdcall GetVersion()
{
  return(get_version());
}
extern "C" void* __stdcall DoCreateModel(void)
{
return (void*)new AME_model;
}
*/

/* GetNodeCount.... in realta' torna la stessa cosa di get_count...
  ... ma per il momento e' troppo pesante e quindi questa 
e' piu' comoda per ora!!

--- dichiaramole __declspacc come piace a lui cosi' il simile+MinchW non rompe ----
*/
#ifdef WIN32
extern "C" __declspec( dllexport ) 
/*extern "C"  __stdcall */

int GetNodeCount(void* useClassPtr)
{
return((sizeof nodedata)/sizeof(node_data_line));
}

struct pass_data_line {
  char   name[16];
  int    datatype;
  int    eval;
  int    dims[32];
  int    path[32];
  int    graph;
  double min;
  double def;
  double max;
  int    compclass;
  char   caption[256];
};

extern "C" __declspec( dllexport ) 
/*extern "C" __stdcall */ int GetNodeData(int n,struct pass_data_line *PassStruct)
{ 
int i;
strcpy(PassStruct->name ,nodedata[n].name);
PassStruct->datatype =nodedata[n].datatype;
PassStruct->eval =nodedata[n].eval;
for(i=0;i<32;i++)
{
PassStruct->dims[i] =nodedata[n].dims[i];
PassStruct->path[i] =nodedata[n].path[i];
}
PassStruct->graph =nodedata[n].graph;
PassStruct->min =nodedata[n].min;
/* PassStruct->def =nodedata[n].def; */
PassStruct->max =nodedata[n].max;
PassStruct->compclass =nodedata[n].compclass;
strcpy(PassStruct->caption ,nodedata[n].strings[0]);
return n;
}
#endif

